# Generated by Django 5.2.1 on 2025-05-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_address_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telephone',
        ),
    ]
