# Generated by Django 4.2.21 on 2025-05-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "userprofile",
            "0003_remove_userprofile_address_remove_userprofile_gender_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="age",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="salary",
        ),
    ]
