# Generated by Django 4.2.21 on 2025-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_savingoptions_product'),
        ('userprofile', '0004_remove_userprofile_age_remove_userprofile_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_deposits',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='finance.depositproducts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_savings',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='finance.savingproducts'),
        ),
    ]
