# Generated by Django 4.2.21 on 2025-05-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_userprofile_liked_deposits_userprofile_liked_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
    ]
