# Generated by Django 4.2.21 on 2025-05-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_remove_userprofile_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="asset",
            field=models.PositiveIntegerField(default=0, help_text="자산 (원 단위)"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salary",
            field=models.PositiveIntegerField(default=0, help_text="연봉 (원 단위)"),
        ),
    ]
