# Generated by Django 4.2.21 on 2025-05-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_userprofile_asset_userprofile_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="asset",
            field=models.PositiveIntegerField(
                blank=True, help_text="자산 (원 단위)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="salary",
            field=models.PositiveIntegerField(
                blank=True, help_text="연봉 (원 단위)", null=True
            ),
        ),
    ]
