# Generated by Django 4.2.21 on 2025-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_alter_userprofile_asset_alter_userprofile_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
