# Generated by Django 5.2.1 on 2025-05-23 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepositProducts",
            fields=[
                ("dcls_month", models.TextField()),
                ("fin_co_no", models.TextField()),
                ("kor_co_nm", models.TextField()),
                (
                    "fin_prdt_cd",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("fin_prdt_nm", models.TextField()),
                ("join_way", models.TextField()),
                ("mtrt_int", models.FloatField()),
                ("spcl_cnd", models.TextField()),
                ("join_deny", models.IntegerField()),
                ("join_member", models.TextField()),
                ("etc_note", models.TextField()),
                ("max_limit", models.TextField()),
                ("dcls_strt_day", models.TextField()),
                ("dcls_end_day", models.TextField()),
                ("fin_co_subm_day", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SavingProducts",
            fields=[
                ("dcls_month", models.TextField()),
                ("fin_co_no", models.TextField()),
                ("kor_co_nm", models.TextField()),
                (
                    "fin_prdt_cd",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("fin_prdt_nm", models.TextField()),
                ("join_way", models.TextField()),
                ("mtrt_int", models.FloatField()),
                ("spcl_cnd", models.TextField()),
                ("join_deny", models.IntegerField()),
                ("join_member", models.TextField()),
                ("etc_note", models.TextField()),
                ("max_limit", models.TextField()),
                ("dcls_strt_day", models.TextField()),
                ("dcls_end_day", models.TextField()),
                ("fin_co_subm_day", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DepositOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField()),
                ("intr_rate_type", models.TextField()),
                ("intr_rate_type_nm", models.CharField(max_length=100)),
                ("save_trm", models.IntegerField()),
                ("intr_rate", models.FloatField()),
                ("intr_rate2", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.depositproducts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavingOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField()),
                ("intr_rate_type", models.TextField()),
                ("intr_rate_type_nm", models.CharField(max_length=100)),
                ("rsrv_type", models.TextField()),
                ("rsrv_type_nm", models.TextField()),
                ("save_trm", models.IntegerField()),
                ("intr_rate", models.FloatField()),
                ("intr_rate2", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.depositproducts",
                    ),
                ),
            ],
        ),
    ]
