# Generated by Django 5.2.1 on 2025-05-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_depositproducts_mtrt_int_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositproducts",
            name="max_limit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savingproducts",
            name="max_limit",
            field=models.TextField(blank=True, null=True),
        ),
    ]
