# Generated by Django 5.2.1 on 2025-05-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_depositproducts_max_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositproducts",
            name="dcls_end_day",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savingproducts",
            name="dcls_end_day",
            field=models.TextField(blank=True, null=True),
        ),
    ]
