# Generated by Django 5.2.1 on 2025-05-23 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_depositproducts_dcls_end_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingoptions",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.savingproducts"
            ),
        ),
    ]
