# Generated by Django 4.2.21 on 2025-05-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="category",
            field=models.IntegerField(default=2),
        ),
    ]
