# Generated by Django 4.2.21 on 2025-05-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_community_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedCommunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.TextField()),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("category", models.IntegerField()),
            ],
        ),
    ]
